#用途declare/impact
usage: 'generate'
#标签名
tagName: 'example'
#标签归属用户名
tagOwner: 'yejiaquan'
#标签归属用户密码
tagPassword: '123456'
#标签来源mysql host
host: '115.28.216.244'
#标签来源mysql 用户名
user: 'evan'
#数据来源mysql 密码
password: '123456'
#数据来源表名/视图名
database: 'impact'
#数据包/元数据存储位置
path: '/Users/yejiaquan/Code/Company/Impact/impact'
#接收到的meta内容
meta: ''
#混淆
salt: 'abcdefgh'
#数据包及meta目录
file: ''
#数据库查询语句
sql: 'select * from test where col != 13540968437'
#选择需要存储的列名
colName: 'id,col'
#declare/impact目标服务器
serverAddress: '127.0.0.1:8080'