#------运行时传入的参数------
#用途declare/impact/...
usage: ''
#标签名
tagName: ''
#数据库查询语句
sql: ''
#选择需要加密存储的列名
encryptedColumn: ''
#选择不需要加密存储的列名
unencryptedColumn: ''
#混淆
salt: ''
#JobID
job: ''
#数据包及meta目录
file: ''
#以文件作为数据源时需要传入的分隔符
separator: ''
#以文件作为数据源时需要自定义的列名，逗号分隔
columnName: ''
#数据来源文件
sourceFile: ''
#保留，若上传失败则为文件数量
n: ''

#------配置文件中覆盖的值------
#数据包/元数据存储位置
path: ''
#declare/impact目标服务器
serverAddress: '20.26.25.211:8082'
#一次从数据取数的量（根据内存容量自行调节
fetchSize: '100'