#------需要手动调节的数值------
#标签归属用户名
tagOwner: 'yejiaquan'
#标签归属用户密码
tagPassword: '123456'
#标签来源mysql host
host: '115.28.216.244'
#标签来源mysql 用户名
dbUser: 'evan'
#数据来源mysql 密码
dbPassword: '123456'
#数据库名
database: 'impact'
#一次从数据取数的量（根据内存容量自行调节
fetchSize: '1000'

#------建议保持不变的数值------
#数据包/元数据存储位置
path: '/Users/yejiaquan/Code/Company/Impact/impact'
#declare/impact目标服务器
serverAddress: '127.0.0.1:8080'

#------运行中会传入的数值------
#用途declare/impact
usage: ''
#标签名
tagName: 'we'
#数据库查询语句
sql: 'select * from test limit 123'
#选择需要存储的列名
colName: ''
#混淆
salt: ''
#JobID
job: ''
#数据包及meta目录
file: ''