#------需要手动调节的数值------
#基于的配置文件
settingBase: 'base'
#标签归属用户名
tagOwner: 'yejiaquan'
#标签归属用户密码
tagPassword: '123456'
#标签来源mysql host
host: '115.28.216.244'
#标签来源mysql 用户名
dbUser: 'evan'
#数据来源mysql 密码
dbPassword: '123456'
#数据库名
database: 'impact'
#一次从数据取数的量（根据内存容量自行调节
fetchSize: '1000'