#------运行时传入的参数------
#用途declare/impact/...
usage: ''
#标签名
tagName: ''
#数据库查询语句
sql: ''
#选择需要加密存储的列名
encryptedColumn: ''
#选择不需要加密存储的列名
unencryptedColumn: ''
#混淆
salt: ''
#JobID
job: ''
#数据包及meta目录
file: ''

#------配置文件中覆盖的值------
#数据包/元数据存储位置
path: ''
#declare/impact目标服务器
serverAddress: ''
#一次从数据取数的量（根据内存容量自行调节
fetchSize: '100'